### ISSUE TITLE
Move getMonths and getYears to a package

### ISSUE THREAD

**Issue by spencerlambert** [mdisc/wisp-central-control#8]
We need to create a mdisc:dates package that has the getMonths and getYears functions used by the stripe package.

We could also add the steeve:moment-dateformat package to mdisc:dates.  The mdisc:manage-account package uses this.

The idea is to create a common package that handles things related to dates.  Future items might be to include a data picker.

**Comment by sr-wisptools-vivek** [comment]
Created the "mdisc:dates" package.
Added "steeve:moment-dateformat" package to "mdisc:dates".
Added functions getMonths and getYears from Stripe package.

**Comment by sr-wisptools-vivek** [comment]
Committed the code to "issue#8" branch in my Fork and created a pull request.
